language: php
sudo: required

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
#  - hhvm

install:
  - composer install

before_script:
  - sudo apt-get update
  - ./build/install_fpm_$(phpenv version-name).sh

script: phpunit -c phpunit.xml.dist

after_failure:
  - cat apache_error.log
  - cat apache_access.log

after_script:
  ## Code climate
  - ./vendor/bin/test-reporter
